api_key = ""
collectors = ["cpu","diskstats","if","loadavg","vm"]
debug = false
debug_cgm = false
debug_dump_metrics = ""
listen = []
listen_socket = []
plugin_ttl_units = "s"

plugin_packages = []

[api]
ca_file = ""
url = "https://api.circonus.com/v2/"

[check]
broker = "select"
bundle_id = ""
create = false
enable_new_metrics = false
metric_refresh_ttl = "5m"
tags = ""

[log]
level = "info"
pretty = false

[reverse]
broker_ca_file = ""
enabled = true

[ssl]
listen = ""
verify = true

[statsd]
disabled = false
port = "8125"

[statsd.group]
check_bundle_id = ""
counters = "sum"
gauges = "average"
metric_prefix = "group."
sets = "sum"

[statsd.host]
category = "statsd"
metric_prefix = "host."
