
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# need to add a constraint on go-ole for wmi
# wmi uses "master" rather than the semver release of go-ole
required = ["github.com/go-ole/go-ole"]

[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/units"

[[constraint]]
  name = "github.com/circonus-labs/circonus-gometrics"
  version = "2.1.0"

[[constraint]]
  name = "github.com/maier/go-appstats"
  version = "0.2.0"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/tomb.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "xi2.org/x/httpgzip"

# need to add a constraint on go-ole for wmi
# wmi uses "master" rather than the semver release of go-ole
[[constraint]]
    name = "github.com/go-ole/go-ole"
    branch = "master"
